language: java
jdk:
  - oraclejdk8
sudo: false
install: true
git:
  depth: 3

script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure:
  app:
    feature_deploy_heroku_travis: users-microservice-example
  on:
    repo: ismaelcabanas/docker-microservice-example