language: java

jdk:
  - oraclejdk8

sudo: false # build faster

install: true # skip the installation step

git:
  depth: 3 # Travis CI clones git repos to a depth of 50 commits

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"

script:
  mvn clean verify -Pheroku
