server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---

spring:
  profiles: heroku
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: ${PORT}