server:
  port: 8080

---

spring:
  profiles: heroku
  jpa:
    generate-ddl: true
    hibernate:
       ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: ${PORT}